---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: harsh
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "harshmt2023164/calculator"
        source: pull
      register: docker_pull_result
   - name: Your Playbook
     hosts: localhost
     gather_facts: true
     tasks:
      - name: Gathering Facts
        ansible.builtin.setup:
        gather_subset: all
        gather_timeout: 30

    environment:
       ANSIBLE_HOST_KEY_CHECKING: "False"

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name calc_container harshmt2023164/calculator
